/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package practica12smm;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Point2D;
import java.awt.image.BufferedImage;
import sm.mva.graficos.MiElipse2D;
import sm.mva.graficos.MiLinea2D;
import sm.mva.iu.Lienzo2D;

/**
 *
 * @author Manuel Vico
 */
public class dialogDiagrama extends javax.swing.JDialog {
    /**
     * Creates new form dialogDiagrama
     */
    public dialogDiagrama() {
        initComponents();
        this.setTitle("Función de Transformación");
        
    }

    public Lienzo2D getLienzo2D() {
        return lienzo2D;
    }

    public void setLienzo2D(Lienzo2D lienzo2D) {
        this.lienzo2D = lienzo2D;
    }
    
    
    public void cambioFuncion(double vA, double vB){
        BufferedImage img;
        img = new BufferedImage(255, 255, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2d = img.createGraphics();
        g2d.setColor(Color.WHITE);
        g2d.fillRect(0, 0, img.getWidth(), img.getHeight());
        
        
        RenderingHints render = new RenderingHints(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);
        g2d.setRenderingHints(render);
        g2d.setColor(Color.BLACK);
        
        Point2D p1 = new Point2D.Double(0, 255);
        Point2D p2 = new Point2D.Double(vA, 255-vB);
        Point2D p3 = new Point2D.Double(255, 0);
        MiLinea2D linea1 = new MiLinea2D(p1, p2);
        MiLinea2D linea2 = new MiLinea2D(p2, p3);
        
        Ellipse2D punto = new Ellipse2D.Double(vA-3, 252-vB, 6, 6);
        g2d.draw(punto);
        
        g2d.draw(linea1);
        g2d.draw(linea2);
        this.getLienzo2D().setImagen(img);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lienzo2D = new sm.mva.iu.Lienzo2D();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(272, 272));

        javax.swing.GroupLayout lienzo2DLayout = new javax.swing.GroupLayout(lienzo2D);
        lienzo2D.setLayout(lienzo2DLayout);
        lienzo2DLayout.setHorizontalGroup(
            lienzo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );
        lienzo2DLayout.setVerticalGroup(
            lienzo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );

        getContentPane().add(lienzo2D, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private sm.mva.iu.Lienzo2D lienzo2D;
    // End of variables declaration//GEN-END:variables
}
