/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package practica12smm;

import java.awt.Color;
import java.awt.image.BufferedImage;
import sm.mva.iu.Lienzo2D;

/**
 * Esta clase define una Ventana Interna con un Lienzo2D para dibujar formas
 * 
 * @author Manuel Vico
 */
public class VentanaInternaImagen extends javax.swing.JInternalFrame {
    
    private String cadenaVacia = "";
    private final VentanaPrincipal principal;
    
    /**
     * Constructor de la clase VentanaInterna, 
     * donde se inicializan sus componentes
     * @param principal
     */
    public VentanaInternaImagen(VentanaPrincipal principal) {
        this.principal = principal;
        initComponents();
    }

    
    /**
     * Método que devuelve el Lienzo2D de esta VentanaInternaImagen
     * 
     * @return el componente Lienzo2D
     */
    public Lienzo2D getLienzo2D() {
        return lienzo2D;
    }
    
    /**
     * Método que establece el Lienzo2D de esta VentanaInternaImagen
     * 
     * @param lienzo2D el Lienzo2D que se quiere establecer
     */
    public void setLienzo2D(Lienzo2D lienzo2D) {
        this.lienzo2D = lienzo2D;
    }
    
    private boolean estaEnImagen(int x, int y){
        boolean dentro = false;
        BufferedImage img = this.getLienzo2D().getImagen();
        int ancho = img.getWidth();
        int alto = img.getHeight();
        if(x >= 0 && x < ancho && y >= 0 && y < alto)
            dentro = true;
        
        return dentro;
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lienzo2D = new sm.mva.iu.Lienzo2D();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        lienzo2D.setBackground(new java.awt.Color(255, 255, 255));
        lienzo2D.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lienzo2DMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lienzo2DMouseMoved(evt);
            }
        });
        lienzo2D.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lienzo2DMouseExited(evt);
            }
        });

        javax.swing.GroupLayout lienzo2DLayout = new javax.swing.GroupLayout(lienzo2D);
        lienzo2D.setLayout(lienzo2DLayout);
        lienzo2DLayout.setHorizontalGroup(
            lienzo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        lienzo2DLayout.setVerticalGroup(
            lienzo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 262, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(lienzo2D);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lienzo2DMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzo2DMouseDragged
        String coordenadas = "X: " + evt.getX() + " Y: " + evt.getY();
        this.principal.setTextCoordenadas(coordenadas);
        
        if(estaEnImagen(evt.getX(), evt.getY())){
            BufferedImage img = this.getLienzo2D().getImagen();
            Color color = new Color(img.getRGB(evt.getX(), evt.getY()));
            String textorgb = "R: " + color.getRed() + ", G: " + color.getGreen() + ", B: " + color.getBlue();
            this.principal.setTextRGB(textorgb);
        }
    }//GEN-LAST:event_lienzo2DMouseDragged

    private void lienzo2DMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzo2DMouseMoved
        String coordenadas = "X: " + evt.getX() + " Y: " + evt.getY();
        this.principal.setTextCoordenadas(coordenadas);
        
        if(estaEnImagen(evt.getX(), evt.getY())){
            BufferedImage img = this.getLienzo2D().getImagen();
            Color color = new Color(img.getRGB(evt.getX(), evt.getY()));
            String textorgb = "R: " + color.getRed() + ", G: " + color.getGreen() + ", B: " + color.getBlue();
            this.principal.setTextRGB(textorgb);
        }
    }//GEN-LAST:event_lienzo2DMouseMoved

    private void lienzo2DMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzo2DMouseExited
        this.principal.setTextCoordenadas(cadenaVacia);
        this.principal.setTextRGB(cadenaVacia);
    }//GEN-LAST:event_lienzo2DMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private sm.mva.iu.Lienzo2D lienzo2D;
    // End of variables declaration//GEN-END:variables
}
